version: '2'
services:
  app:
    build:
      context: .
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
    environment:
      NODE_ENV: development
      BASIC_USER: depot
      BASIC_PASSWORD: depot
    ports:
      - '3000:3000'
    volumes:
      - ./public/ftp:/opt/app-root/src/depot/public/ftp
      - ./config:/opt/app-root/src/depot/config
