version: '2'
services:
  app:
    build: .
    environment:
      NODE_ENV: development
    ports:
      - '3000:3000'
    volumes:
      - ./public/ftp:/opt/app-root/src/express/public/ftp
      - ./config:/opt/app-root/src/express/config
