Directory:
  - Test/7
  - Stable/7
  - Tool/7
  - Documents
  - Pictures

Operate:
  -
    match: .+\.noarch\.rpm
    rename: x86_64/Packages/${filename}
    post: createrepo ${dir_0}
    break: true
  -
    match: .+\.(.+)\.rpm
    rename: ${match_1}/Packages/${filename}
    post: createrepo ${dir_0}
    break: true
