Operate:
  Upload:
    -
      rename:
        src: ${filepath}
        dest: ${dest}/${filename}
    -
      create: fileList
    -
      match: .+\.rpm
      exec: createrepo ${dest}/..
  Remove:
    -
      unlink: ${filepath}
    -
      create: fileList
    -
      match: .+\.rpm
      exec: createrepo ${dirname}/..

List:
  ignore:
    - repodata
    - .cache
