Operate:
  Upload:
    -
      rename:
        src: ${filepath}
        dest: ${basedir}/${dest}/${filename}
    -
      create: fileList
    -
      match: .+\.rpm
      exec: createrepo ${basedir}/${dest}/..
  Remove:
    -
      unlink: ${basedir}/${filepath}
    -
      create: fileList
    -
      match: .+\.rpm
      exec: createrepo ${basedir}/${dirname}/..

List:
  ignore:
    - repodata
    - .cache
