Directory:
  - Test/7
  - Stable/7
  - Tool/7
  - Documents
  - Pictures

Operate:
  Upload:
    -
      match: .+\.rpm
      rename: Packages/${filename}
      post: createrepo ${dirname}/..
    -
      rename: ${filename}
  Remove:
    -
      match: .+\.rpm
      post: createrepo ${dirname}/..

List:
  exclude:
    - repodata
