Operate:
  Upload:
    -
      rename:
        src: ${filepath}
        dest: ${basedir}/${dest}/${filename}
    -
      create:
        fileList:
          src: ${basedir}
          dest: ${basedir}/.cache/files.json
    -
      match: .+\.rpm
      exec: createrepo ${basedir}/${dest}/..
  Remove:
    -
      unlink: ${basedir}/${filepath}
    -
      create:
        fileList:
          src: ${basedir}
          dest: ${basedir}/.cache/files.json
    -
      match: .+\.rpm
      exec: createrepo ${basedir}/${dirname}/..

List:
  ignore:
    - repodata
    - .cache
  path: ${basedir}/.cache/files.json
  create:
    fileList:
      src: ${basedir}
      dest: ${basedir}/.cache/files.json
