Directory:
  - Test/7
  - Stable/7
  - Tool/7
  - Documents
  - Pictures

Operate:
  Upload:
    -
      match: .+\.noarch\.rpm
      rename: x86_64/Packages/${filename}
      post: createrepo ${dirname}/..
      break: true
    -
      match: .+\.(.+)\.rpm
      rename: ${match_1}/Packages/${filename}
      post: createrepo ${dirname}/..
      break: true

List:
  exclude:
    - repodata
