Directory:
  - Test/7
  - Stable/7
  - Tool/7
  - Documents
  - Pictures

Operate:
  Upload:
    -
      rename: ${dest}/${filename}
    -
      match: .+\.rpm
      post: createrepo ${dirname}/..
  Remove:
    -
      match: .+\.rpm
      post: createrepo ${dirname}/..

List:
  exclude:
    - repodata
