Directory:
  - Test/7
  - Stable/7
  - Tool/7
  - Documents
  - Pictures

Operate:
  Upload:
    -
      rename:
        src: ${filepath}
        dest: ${dest}/${filename}
    -
      create: fileList
    -
      match: .+\.rpm
      exec: createrepo ${dest}/..
  Remove:
    -
      unlink: ${filepath}
    -
      create: fileList
    -
      match: .+\.rpm
      exec: createrepo ${dirname}/..

List:
  ignore:
    - repodata
    - .cache
